/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'antoniomaria' at '12.3.2016 22:52' with Gradle 2.11
 *
 * @author antoniomaria, @date 12.3.2016 22:52
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  def library = new Library()

  test("pascal triangle") {
    assertResult(1)(library.pascal(2, 0));
    // assertResult(2)(library.pascal(1, 2));
    //assertResult(3)(library.pascal(1, 3));
  }

  test("someLibraryMethod is always true") {

    assertResult(true)(library.balance("I told him (that it’s not (yet) done). (But he wasn’t listening)".toList))

    assertResult(false)(library.balance("())(".toList))
    assertResult(true)(library.balance("(if (zero? x) max (/ 1 x))".toList))

  }
}
